FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
EXPOSE 6001
ENV ASPNETCORE_URLS=http://*:6001

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /
COPY . .
RUN dotnet restore "LearnIt.Courses.sln"
RUN dotnet build "LearnIt.Courses.sln" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LearnIt.Courses.WebHost/LearnIt.Courses.WebHost.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish ./
ENTRYPOINT ["dotnet", "LearnIt.Courses.WebHost.dll"]